spring:
  application:
    name: account-service
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kurly_account
    username: root

server:
  servlet:
    session:
      tracking-modes: cookie

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  packages-to-scan: com.kurly.kurlyaccount.account.api
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true