spring:
  application:
    name: account-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create
  datasource:
    url: 'jdbc:h2:mem:kurly_account'
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: '/h2-console'