spring:
  application:
    name: account-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create
  datasource:
    url: 'jdbc:h2:mem:kurly_account'
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: '/h2-console'

server:
  servlet:
    session:
      tracking-modes: cookie

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  packages-to-scan: com.kurly.kurlyaccount.account.api
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true